Repository SFDigitalServices/sf-dahlia-lap, pull requests merged in 2018-08, with the labels that each got.

#46 Features/lease ups page #154064502
  app/assets/stylesheets/lap.scss
  app/assets/stylesheets/pattern-library.scss
  app/controllers/listings/applications_controller.rb
  app/controllers/listings/lease_ups/applications_controller.rb
  app/controllers/listings/lease_ups_controller.rb
  app/javascript/components/lease_ups/LeaseUpApplicationsPage.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTable.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTableContainer.js
  app/javascript/components/lease_ups/LeaseUpListingsPage.js
  app/javascript/components/lease_ups/LeaseUpListingsTable.js
  app/javascript/components/lease_ups/StatusModalWrapper.js
  app/javascript/components/mappers/soqlToDomain/listing.js
  app/javascript/components/mappers/utils.js
  app/javascript/components/supplemental_application/SupplementalApplicationHeader.js
  app/javascript/components/supplemental_application/SupplementalApplicationPage.js
  app/javascript/packs/react_application.js
  app/javascript/utils/appPaths.js
  app/javascript/utils/reactTableUtils.js
  app/services/force/lease_up_service.rb
  app/views/layouts/_navigation_links.html.slim
  app/views/listings/lease_ups/applications/index.html.slim
  app/views/listings/lease_ups/index.slim
  config/routes.rb
  config/salesforce/fields/lease_ups.yml
  spec/javascript/components/lease_ups/LeaseUpsPage.test.js
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpsPage.test.js.snap
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
Labels: accepted

#50 Features/add alice griffith confirmed preference #157446687
  app/javascript/components/lease_ups/LeaseUpApplicationsTable.js
  app/javascript/components/supplemental_application/sections/PreferencesTable.js
  app/services/force/lease_up_service.rb
Labels: accepted

#61 Bugs/live work preference document types #159241591
  app/javascript/components/applications/application_form/formOptions.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/PreferenceAdditionalOptions.js
  app/javascript/components/applications/application_form/preferences/PreferenceForm.js
  app/javascript/components/applications/application_form/preferences/PreferencesSection.js
Labels: caritas feedback release

#64 Features/add language submitted #159338128
  app/controllers/api/v1/short_form_controller.rb
  app/javascript/components/applications/application_form/ApplicationLanguageSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/formOptions.js
  app/javascript/components/applications/applicationsPageMapper.js
  app/javascript/components/mappers/domainToApiFields.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/fixtures/short_form_submit_payload.js
Labels: caritas feedback release

#60 Features/update date input #157785070
  app/javascript/components/applications/application_form/DatePickerText.js
  app/javascript/components/applications/application_form/HouseholdMemberForm.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/packs/react-datepicker.js
  app/views/applications/edit.html.slim
  app/views/listings/applications/new.html.slim
  package.json
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  yarn.lock
Labels: caritas feedback release

#73 features/caritas-add-address-to-alternate-contact-#159338204
  app/javascript/components/applications/ApplicationPage.js
  app/javascript/components/applications/application_form/AddressForm.js
  app/javascript/components/applications/application_form/AlternateContactSection.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/applications/application_form/utils.js
  app/javascript/components/mappers/domainToApi.js
  app/javascript/components/mappers/domainToApiFields.js
  app/javascript/utils/objectUtils.js
  config/salesforce/fields.yml
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
Labels: caritas feedback release

#77 Features/caritas button to create new app #159246205
  app/assets/stylesheets/pattern-library.scss
  app/javascript/components/applications/ApplicationPage.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/layouts/CardLayout.js
  app/javascript/components/organisms/PageHeader.js
  app/javascript/utils/appPaths.js
  app/views/applications/show.html.slim
  spec/javascript/components/applications/__snapshots__/ApplicationPage.test.js.snap
Labels: caritas feedback release

#78 features/caritas-validate-preferences-paper-application-#159245564
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/applications/application_form/preferences/AliceGriffithFields.js
  app/javascript/components/applications/application_form/preferences/AntiDisplacementFields.js
  app/javascript/components/applications/application_form/preferences/CertOfPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DefaultPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DisplacedFields.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/NeighborhoodResidentFields.js
  app/javascript/components/applications/application_form/preferences/PreferenceAdditionalOptions.js
  app/javascript/components/applications/application_form/preferences/PreferenceForm.js
  app/javascript/components/applications/application_form/preferences/RentBurdenedAssistedHousingFields.js
  app/javascript/components/atoms/Column.js
  app/javascript/utils/form/Field.js
  app/javascript/utils/form/errors.js
  app/javascript/utils/form/validations.js
  app/javascript/utils/reactFormUtils.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
Labels: accepted, caritas feedback release

#80 Features/caritas required name fields #159244905
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
Labels: accepted, caritas feedback release

#74 [DO NOT MERGE] caritas-feedback-release <-> master comparison
  app/assets/stylesheets/pattern-library.scss
  app/controllers/api/v1/short_form_controller.rb
  app/javascript/components/applications/ApplicationPage.js
  app/javascript/components/applications/application_form/AddressForm.js
  app/javascript/components/applications/application_form/AlternateContactSection.js
  app/javascript/components/applications/application_form/ApplicationLanguageSection.js
  app/javascript/components/applications/application_form/DatePickerText.js
  app/javascript/components/applications/application_form/HouseholdMemberForm.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/applications/application_form/formOptions.js
  app/javascript/components/applications/application_form/preferences/AliceGriffithFields.js
  app/javascript/components/applications/application_form/preferences/AntiDisplacementFields.js
  app/javascript/components/applications/application_form/preferences/CertOfPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DefaultPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DisplacedFields.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/NeighborhoodResidentFields.js
  app/javascript/components/applications/application_form/preferences/PreferenceAdditionalOptions.js
  app/javascript/components/applications/application_form/preferences/PreferenceForm.js
  app/javascript/components/applications/application_form/preferences/PreferencesSection.js
  app/javascript/components/applications/application_form/preferences/RentBurdenedAssistedHousingFields.js
  app/javascript/components/applications/application_form/utils.js
  app/javascript/components/applications/applicationsPageMapper.js
  app/javascript/components/atoms/Column.js
  app/javascript/components/layouts/CardLayout.js
  app/javascript/components/mappers/domainToApi.js
  app/javascript/components/mappers/domainToApiFields.js
  app/javascript/components/organisms/PageHeader.js
  app/javascript/packs/react-datepicker.js
  app/javascript/utils/appPaths.js
  app/javascript/utils/form/Field.js
  app/javascript/utils/form/errors.js
  app/javascript/utils/form/validations.js
  app/javascript/utils/objectUtils.js
  app/javascript/utils/reactFormUtils.js
  app/views/applications/edit.html.slim
  app/views/applications/show.html.slim
  app/views/listings/applications/new.html.slim
  config/salesforce/fields.yml
  package.json
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationPage.test.js.snap
  spec/javascript/fixtures/short_form_submit_payload.js
  yarn.lock
Labels: do not merge, wip

#82 Bugs/add and save preference bugs #159943362
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/preferences/AliceGriffithFields.js
  app/javascript/components/applications/application_form/preferences/AntiDisplacementFields.js
  app/javascript/components/applications/application_form/preferences/CertOfPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DefaultPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DisplacedFields.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/NeighborhoodResidentFields.js
  app/javascript/components/applications/application_form/preferences/RentBurdenedAssistedHousingFields.js
  app/javascript/utils/form/validations.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
Labels: caritas feedback release

#86 Merge Caritas Updates
  app/controllers/api/v1/short_form_controller.rb
  app/javascript/components/applications/ApplicationNewPage.js
  app/javascript/components/applications/ApplicationPage.js
  app/javascript/components/applications/actions.js
  app/javascript/components/applications/application_details/fields.js
  app/javascript/components/applications/application_form/AddressForm.js
  app/javascript/components/applications/application_form/AlternateContactSection.js
  app/javascript/components/applications/application_form/ApplicationLanguageSection.js
  app/javascript/components/applications/application_form/DatePickerText.js
  app/javascript/components/applications/application_form/HouseholdMemberForm.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/applications/application_form/formOptions.js
  app/javascript/components/applications/application_form/preferences/AliceGriffithFields.js
  app/javascript/components/applications/application_form/preferences/AntiDisplacementFields.js
  app/javascript/components/applications/application_form/preferences/CertOfPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DefaultPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DisplacedFields.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/NeighborhoodResidentFields.js
  app/javascript/components/applications/application_form/preferences/PreferenceAdditionalOptions.js
  app/javascript/components/applications/application_form/preferences/PreferenceForm.js
  app/javascript/components/applications/application_form/preferences/PreferencesSection.js
  app/javascript/components/applications/application_form/preferences/RentBurdenedAssistedHousingFields.js
  app/javascript/components/applications/application_form/utils.js
  app/javascript/components/atoms/Column.js
  app/javascript/components/layouts/CardLayout.js
  app/javascript/components/mappers/domainToApi/alternateContact.js
  app/javascript/components/mappers/domainToApi/application.js
  app/javascript/components/mappers/domainToApiFields.js
  app/javascript/components/organisms/PageHeader.js
  app/javascript/packs/react-datepicker.js
  app/javascript/utils/appPaths.js
  app/javascript/utils/form/Field.js
  app/javascript/utils/form/errors.js
  app/javascript/utils/form/validations.js
  app/javascript/utils/objectUtils.js
  app/javascript/utils/reactFormUtils.js
  app/views/applications/edit.html.slim
  app/views/applications/show.html.slim
  app/views/listings/applications/new.html.slim
  config/salesforce/fields/applications.yml
  package.json
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationPage.test.js.snap
  spec/javascript/fixtures/application.js
  spec/javascript/fixtures/short_form_submit_payload.js
  spec/javascript/fixtures/supplemental_submit_payload.js
  yarn.lock
Labels: paired
