Repository SFDigitalServices/sf-dahlia-lap, pull requests merged in 2019-06, with the labels that each got.

#256 Currency fields #165205282
  app/javascript/components/applications/application_form/HouseholdIncomeSection.js
  app/javascript/components/mappers/soqlToDomain/application.js
  app/javascript/components/supplemental_application/SupplementalApplicationPage.js
  app/javascript/components/supplemental_application/sections/ConfirmedHouseholdIncome.js
  app/javascript/components/supplemental_application/sections/LeaseInformationInputs.js
  app/javascript/components/supplemental_application/sections/RentalAssistance.js
  app/javascript/utils/form/final_form/Field.js
  app/javascript/utils/formUtils.js
  app/javascript/utils/utils.js
  app/models/force/lease.rb
  app/models/force/object_base.rb
  app/models/force/rental_assistance.rb
  spec/fixtures/controllers/supplementals/index.json
  spec/fixtures/model/force/lease/lease_domain.json
  spec/fixtures/model/force/lease/lease_domain_to_salesforce.json
  spec/fixtures/model/force/lease/lease_salesforce_soql.json
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/components/supplemental_application/sections/__snapshots__/RentalAssistance.test.js.snap
  spec/javascript/e2e/SupplementalApplicationPage/confirmed_household.e2e.js
  spec/javascript/e2e/SupplementalApplicationPage/lease_information.e2e.js
  spec/javascript/e2e/SupplementalApplicationPage/rental_assistance.e2e.js
  spec/javascript/fixtures/application_api_edit_payload.js
  spec/javascript/fixtures/short_form_submit_payload.js
  spec/javascript/fixtures/supplemental_submit_payload.js
  spec/javascript/utils/formUtils.test.js
  spec/model/force/lease_spec.rb
Labels: accepted

#260 Additional Paper App fields required #165475824
  app/assets/stylesheets/toolkit.scss
  app/javascript/components/applications/application_form/AgreeToTerms.js
  app/javascript/components/applications/application_form/DemographicInfoSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/formOptions.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/e2e/ApplicationNewPage.e2e.js
Labels: accepted

#261 Bug - Open House Inconsistencies 166098541
  app/javascript/components/listings/ListingDetails.js
  app/javascript/components/listings/ListingDetailsContentTable.js
  app/javascript/components/listings/fieldSpecs.js
  app/javascript/utils/fieldSpecs.js
  spec/javascript/components/listing/__snapshots__/ListingPage.test.js.snap
  spec/javascript/factories/models.js
Labels: accepted

#263 Allow toggle of listing showing in lease up section #161968404
  app/services/force/soql/listing_service.rb
  spec/services/force/soql/listing_service_spec.rb
  spec/vcr/services/soql/listing_service.yml
Labels: accepted

#259 Display error alert box on supp app if form is invalid #164615215
  app/javascript/components/supplemental_application/SupplementalApplicationContainer.js
  app/javascript/utils/form/validations.js
  app/models/force/lease.rb
  spec/javascript/components/supplemental_application/SupplementalApplicationPage.test.js
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
Labels: accepted

#249 Require Comments for Status and Substatus #165919789
  app/assets/stylesheets/toolkit.scss
  app/javascript/components/applications/application_form/DemographicInfoSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTableContainer.js
  app/javascript/components/mappers/soqlToDomain/field_update_comment.js
  app/javascript/components/organisms/FormModal.js
  app/javascript/components/organisms/StatusModalWrapper.js
  app/javascript/components/organisms/StatusUpdate.js
  app/javascript/components/supplemental_application/SupplementalApplicationContainer.js
  app/javascript/components/supplemental_application/SupplementalApplicationPage.js
  app/javascript/components/supplemental_application/sections/ConfirmedHouseholdIncome.js
  app/javascript/components/supplemental_application/sections/ConfirmedUnits.js
  app/javascript/components/supplemental_application/sections/RentalAssistance.js
  app/javascript/components/supplemental_application/sections/StatusList.js
  app/javascript/utils/form/final_form/Field.js
  app/javascript/utils/statusUtils.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/components/lease_ups/LeaseUpApplicationsPage.test.js
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpApplicationsPage.test.js.snap
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/components/supplemental_application/sections/__snapshots__/RentalAssistance.test.js.snap
  spec/javascript/e2e/LeaseUpPage.e2e.js
  spec/javascript/support/puppeteer/steps/supplementalApplicationSteps.js
  spec/javascript/utils/statusUtils.js
Labels: needs review

#265 Update sub status options and tests #165920113
  app/assets/stylesheets/toolkit.scss
  app/javascript/components/organisms/FormModal.js
  app/javascript/components/organisms/StatusModalWrapper.js
  app/javascript/utils/statusUtils.js
Labels: needs review

#266 Block edit application lottery rules #157952411
  app/controllers/applications_controller.rb
  app/javascript/components/applications/ApplicationPage.js
  app/javascript/components/applications/application_details/applicationDetailsFieldsDesc.js
  app/javascript/components/mappers/soqlToDomain/application.js
  app/models/force/application.rb
  app/services/force/soql/application_service.rb
  config/salesforce/fields/applications.yml
  spec/controllers/applications_controller_spec.rb
  spec/fixtures/controllers/applications/lease_up_application_domain.json
  spec/fixtures/controllers/applications/non_lease_up_application_domain.json
  spec/fixtures/controllers/applications/sale_application_domain.json
  spec/fixtures/controllers/supplementals/index.json
  spec/fixtures/model/force/application/app_domain_from_salesforce.json
  spec/fixtures/model/force/application/app_salesforce.json
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/e2e/ApplicationEditPage.e2e.js
  spec/javascript/e2e/ApplicationNewPage.e2e.js
  spec/javascript/fixtures/application.js
  spec/javascript/fixtures/supplemental_application.js
  spec/javascript/support/puppeteer/steps/applications.js
  spec/support/force_helpers.rb
  spec/vcr/applications_controller/edit/non_lease_up_application.yml
  spec/vcr/applications_controller/edit/paper_app_lottery_complete_application.yml
  spec/vcr/applications_controller/show/lease_up_application.yml
  spec/vcr/applications_controller/show/non_lease_up_application.yml
  spec/vcr/applications_controller/show/sale_application.yml
  spec/vcr/supplementals_controller/index/supplemental_application.yml
Labels: needs review

#269 Fix flagged app listing dropdown #166685619
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/javascript/components/IndexTable.js
  spec/javascript/components/applications/__snapshots__/ListingApplicationsPage.test.js.snap
  spec/javascript/components/applications/flagged/__snapshots__/FlaggedApplicationsIndexPage.test.js.snap
  spec/javascript/components/listing/__snapshots__/ListingsPage.test.js.snap
Labels: wip
