Repository SFDigitalServices/sf-dahlia-lap, pull requests merged in 2019-04, with the labels that each got.

#210 Show alert when status save fails on lease up apps table #164719710
  app/javascript/components/lease_ups/LeaseUpApplicationsPage.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTableContainer.js
  spec/javascript/components/lease_ups/LeaseUpApplicationsPage.test.js
  spec/javascript/components/lease_ups/LeaseUpsPage.test.js
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpApplicationsPage.test.js.snap
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpsPage.test.js.snap
Labels: needs review

#212 Make 'Select One..' a selectable dropdown option #164620445
  app/javascript/components/applications/application_form/HouseholdIncomeSection.js
  app/javascript/components/applications/application_form/formOptions.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
Labels: needs review

#213 Use MultiDateField for lease start date #163398177
  app/assets/stylesheets/lap.scss
  app/controllers/api/v1/leases_controller.rb
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/supplemental_application/sections/LeaseInformationInputs.js
  app/javascript/utils/form/validations.js
  app/models/force/application.rb
  app/models/force/lease.rb
  app/models/force/object_base.rb
  app/models/force/preference.rb
  spec/fixtures/controllers/supplementals/index.json
  spec/fixtures/model/force/lease/lease_domain.json
  spec/fixtures/model/force/lease/lease_domain_to_salesforce.json
  spec/fixtures/model/force/lease/lease_salesforce_soql.json
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/e2e/ApplicationNewPage.e2e.js
  spec/javascript/utils/form/validations.test.js
  spec/model/force/lease_spec.rb
Labels: needs review

#214 Do not show applications with null lottery numbers in lease-ups table #162001310
  app/services/force/soql/application_service.rb
Labels: needs review

#206 Features/create eligibility information group #162770611
  app/controllers/api/v1/short_form_controller.rb
  app/javascript/components/applications/application_form/EligibilitySection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/mappers/domainToApi/application.js
  app/javascript/components/mappers/soqlToDomain/application.js
  app/javascript/components/mappers/soqlToDomain/listing.js
  app/javascript/utils/form/Field.js
  app/javascript/utils/form/validations.js
  app/models/force/application.rb
  app/services/force/listing_service.rb
  config/salesforce/fields/applications.yml
  config/salesforce/fields/listings.yml
  spec/controllers/listings/applications_controller_spec.rb
  spec/fixtures/controllers/applications/lease_up_application_domain.json
  spec/fixtures/controllers/supplementals/index.json
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/e2e/ApplicationNewPage.e2e.js
  spec/javascript/fixtures/listing.js
  spec/javascript/support/puppeteer/consts.js
  spec/support/force_helpers.rb
  spec/vcr/applications_controller/show/lease_up_application.yml
  spec/vcr/listings/applications_controller/index.yml
  spec/vcr/listings/applications_controller/index_errors.yml
  spec/vcr/listings/applications_controller/new.yml
  spec/vcr/listings/applications_controller/new_sale.yml
  spec/vcr/supplementals_controller/index/supplemental_application.yml
Labels: needs review

#218 [#162591164] Add missing fields to application view
  app/javascript/components/applications/application_details/fields.js
  spec/javascript/components/applications/__snapshots__/ApplicationPage.test.js.snap
  spec/javascript/components/applications/application_details/__snapshots__/ApplicationDetails.test.js.snap
Labels: needs review

#220 Features/add additional phone number to appl #165161032
  app/javascript/components/applications/application_details/fields.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/mappers/domainToApi/applicant.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationPage.test.js.snap
  spec/javascript/components/applications/application_details/__snapshots__/ApplicationDetails.test.js.snap
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/fixtures/application_api_edit_payload.js
  spec/javascript/fixtures/short_form_submit_payload.js
  spec/javascript/fixtures/supplemental_application.js
  spec/javascript/fixtures/supplemental_submit_payload.js
Labels: needs review

#224 Chores/add newrelic #165160788
  Gemfile
  Gemfile.lock
  config/newrelic.yml
Labels: needs review

#225 Alt contact email validation #165393937
  app/javascript/components/applications/actions.js
  app/javascript/components/applications/application_form/AlternateContactSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  config/newrelic.yml
Labels: needs review, release bug

#222 Require language on paper application #162621696
  app/javascript/components/applications/application_form/ApplicationLanguageSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/e2e/ApplicationNewPage.e2e.js
Labels: needs review

#227 Reorder lease up preference status #165205233
  app/javascript/components/supplemental_application/sections/preferences/utils.js
Labels: accepted

#229 Make Email regex match full input field to be valid #165520605
  app/javascript/utils/form/validations.js
  spec/javascript/utils/form/validations.test.js
Labels: needs review

#219 Fix error on revoking expired tokens #162316506
  app/models/user.rb
  app/services/force/base.rb
  app/views/layouts/_user_links.html.slim
  config/initializers/devise.rb
  lib/salesforce_logout_app.rb
  spec/javascript/e2e/Login.e2e.js
Labels: accepted
