Repository SFDigitalServices/sf-dahlia-lap, pull requests merged in 2019-05, with the labels that each got.

#235 Add eligibility section to application details #165294402
  app/controllers/applications_controller.rb
  app/javascript/components/applications/application_details/ApplicationDetails.js
  app/javascript/components/applications/application_details/ApplicationDetailsContentCard.js
  app/javascript/components/applications/application_details/applicationDetailsFieldsDesc.js
  app/javascript/components/applications/application_details/fields.js
  app/javascript/components/listings/ListingDetailsContentCard.js
  app/javascript/utils/arrayUtils.js
  app/services/force/custom_api/lending_institutions_service.rb
  app/services/force/soql/application_service.rb
  spec/controllers/applications_controller_spec.rb
  spec/fixtures/controllers/applications/lease_up_application_domain.json
  spec/fixtures/controllers/applications/non_lease_up_application_domain.json
  spec/fixtures/controllers/applications/sale_application_domain.json
  spec/javascript/components/applications/ApplicationPage.test.js
  spec/javascript/fixtures/sale_application.js
  spec/javascript/utils/ArrayUtils.test.js
  spec/support/force_helpers.rb
  spec/vcr/applications_controller/show/lease_up_application.yml
  spec/vcr/applications_controller/show/non_lease_up_application.yml
  spec/vcr/applications_controller/show/sale_application.yml
Labels: needs review

#243 Fix sentry deploy issues #165978965
  config/webpack/production.js
  package.json
  yarn.lock
Labels: needs review

#242 Removed loader and added saving text #164967254
  README.md
  app/javascript/components/molecules/Dropdown.js
  app/javascript/components/molecules/StatusDropdown.js
  app/javascript/components/organisms/StatusUpdate.js
  app/javascript/components/supplemental_application/SupplementalApplicationContainer.js
  app/javascript/components/supplemental_application/sections/StatusList.js
  package.json
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  yarn.lock
Labels: needs review

#247 Add SubStatus for Application 158365756
  app/assets/stylesheets/lap.scss
  app/controllers/api/v1/field_update_comments_controller.rb
  app/javascript/apiService.js
  app/javascript/components/lease_ups/LeaseUpApplicationsPage.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTable.js
  app/javascript/components/lease_ups/LeaseUpApplicationsTableContainer.js
  app/javascript/components/molecules/StatusDropdown.js
  app/javascript/components/organisms/StatusModalWrapper.js
  app/javascript/components/supplemental_application/SupplementalApplicationPage.js
  app/javascript/utils/statusUtils.js
  app/services/force/field_update_comment_service.rb
  config/salesforce/fields/field_update_comment.yml
  spec/fixtures/controllers/supplementals/index.json
  spec/javascript/components/lease_ups/LeaseUpApplicationsPage.test.js
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpApplicationsPage.test.js.snap
  spec/javascript/support/puppeteer/steps/supplementalApplicationSteps.js
  spec/vcr/supplementals_controller/index/supplemental_application.yml
Labels: needs review

#238 Upgrade paper application to react form #162457306
  app/javascript/components/applications/application_form/AddressForm.js
  app/javascript/components/applications/application_form/AgreeToTerms.js
  app/javascript/components/applications/application_form/AlternateContactSection.js
  app/javascript/components/applications/application_form/ApplicationLanguageSection.js
  app/javascript/components/applications/application_form/DemographicInfoSection.js
  app/javascript/components/applications/application_form/EligibilitySection.js
  app/javascript/components/applications/application_form/HouseholdIncomeSection.js
  app/javascript/components/applications/application_form/HouseholdMemberForm.js
  app/javascript/components/applications/application_form/HouseholdMembersSection.js
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  app/javascript/components/applications/application_form/PrimaryApplicantSection.js
  app/javascript/components/applications/application_form/ReservedPrioritySection.js
  app/javascript/components/applications/application_form/formOptions.js
  app/javascript/components/applications/application_form/preferences/AliceGriffithFields.js
  app/javascript/components/applications/application_form/preferences/AntiDisplacementFields.js
  app/javascript/components/applications/application_form/preferences/CertOfPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DefaultPreferenceFields.js
  app/javascript/components/applications/application_form/preferences/DisplacedFields.js
  app/javascript/components/applications/application_form/preferences/LiveWorkFields.js
  app/javascript/components/applications/application_form/preferences/NeighborhoodResidentFields.js
  app/javascript/components/applications/application_form/preferences/PreferenceAdditionalOptions.js
  app/javascript/components/applications/application_form/preferences/PreferenceForm.js
  app/javascript/components/applications/application_form/preferences/PreferencesSection.js
  app/javascript/components/applications/application_form/preferences/RentBurdenedAssistedHousingFields.js
  app/javascript/components/mappers/soqlToDomain/application_member.js
  app/javascript/components/mappers/utils.js
  app/javascript/utils/form/final_form/Field.js
  app/javascript/utils/form/final_form/MultiDateField.js
  app/javascript/utils/form/validations.js
  package.json
  spec/javascript/components/applications/ApplicationEditPage.test.js
  spec/javascript/components/applications/__snapshots__/ApplicationEditPage.test.js.snap
  spec/javascript/components/applications/__snapshots__/ApplicationNewPage.test.js.snap
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/components/mappers/domainToApi.test.js
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/e2e/ApplicationNewPage.e2e.js
  spec/javascript/fixtures/application_api_edit_payload.js
  spec/javascript/utils/form/validations.test.js
  yarn.lock
Labels: needs review

#248 Add validation to check for valid naturalKey selection #165942084
  app/javascript/components/applications/application_form/PaperApplicationForm.js
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/e2e/ApplicationNewPage.e2e.js
Labels: needs review

#252 Memory Usage config updates #163738628
  Gemfile
  Gemfile.lock
  app/javascript/components/pages/HomePage.js
  config/initializers/oj.rb
  config/puma.rb
  config/scout_apm.yml
Labels: chore/fix, needs review

#253 Unhandled Promise Rejections, Warnings, and Errors for Jest Tests #165754817
  app/javascript/components/IndexTable.js
  app/javascript/components/organisms/Modal.js
  package.json
  spec/javascript/apiService.test.js
  spec/javascript/components/applications/ApplicationEditPage.test.js
  spec/javascript/components/applications/ApplicationNewPage.test.js
  spec/javascript/components/applications/ListingApplicationsPage.test.js
  spec/javascript/components/applications/__snapshots__/ListingApplicationsPage.test.js.snap
  spec/javascript/components/applications/application_form/PaperApplicationForm.test.js
  spec/javascript/components/lease_ups/__snapshots__/LeaseUpApplicationsPage.test.js.snap
  spec/javascript/components/listing/__snapshots__/ListingsPage.test.js.snap
  spec/javascript/components/organisms/__snapshots__/LeaveConfirmationModal.test.js.snap
  spec/javascript/components/organisms/__snapshots__/SimpleModal.test.js.snap
  spec/javascript/components/supplemental_application/SupplementalApplicationPage.test.js
  spec/javascript/components/supplemental_application/__snapshots__/SupplementalApplicationPage.test.js.snap
  spec/javascript/factories/models.js
  spec/javascript/fixtures/listings.js
  yarn.lock
Labels: chore/fix, needs review

#245 Add GNU GPL v3 license
  LICENSE.md
Labels: needs review

#258 Show validation error on "save and new" click #166316461
  app/javascript/components/applications/application_form/PaperApplicationForm.js
Labels: release bug
